// lib/utils/CountryData.dart
import 'CountryClass.dart';

List<Country> getSampleCountries() {
  return [
    Country(name: 'Afghanistan', code: 'AF', phoneCode: '93'),
    Country(name: 'Albania', code: 'AL', phoneCode: '355'),
    Country(name: 'Algeria', code: 'DZ', phoneCode: '213'),
    Country(name: 'American Samoa', code: 'AS', phoneCode: '1-684'),
    Country(name: 'Andorra', code: 'AD', phoneCode: '376'),
    Country(name: 'Angola', code: 'AO', phoneCode: '244'),
    Country(name: 'Anguilla', code: 'AI', phoneCode: '1-264'),
    Country(name: 'Antigua and Barbuda', code: 'AG', phoneCode: '1-268'),
    Country(name: 'Argentina', code: 'AR', phoneCode: '54'),
    Country(name: 'Armenia', code: 'AM', phoneCode: '374'),
    Country(name: 'Aruba', code: 'AW', phoneCode: '297'),
    Country(name: 'Australia', code: 'AU', phoneCode: '61'),
    Country(name: 'Austria', code: 'AT', phoneCode: '43'),
    Country(name: 'Azerbaijan', code: 'AZ', phoneCode: '994'),
    Country(name: 'Bahamas', code: 'BS', phoneCode: '1-242'),
    Country(name: 'Bahrain', code: 'BH', phoneCode: '973'),
    Country(name: 'Bangladesh', code: 'BD', phoneCode: '880'),
    Country(name: 'Barbados', code: 'BB', phoneCode: '1-246'),
    Country(name: 'Belarus', code: 'BY', phoneCode: '375'),
    Country(name: 'Belgium', code: 'BE', phoneCode: '32'),
    Country(name: 'Belize', code: 'BZ', phoneCode: '501'),
    Country(name: 'Benin', code: 'BJ', phoneCode: '229'),
    Country(name: 'Bermuda', code: 'BM', phoneCode: '1-441'),
    Country(name: 'Bhutan', code: 'BT', phoneCode: '975'),
    Country(name: 'Bolivia', code: 'BO', phoneCode: '591'),
    Country(name: 'Bosnia and Herzegovina', code: 'BA', phoneCode: '387'),
    Country(name: 'Botswana', code: 'BW', phoneCode: '267'),
    Country(name: 'Brazil', code: 'BR', phoneCode: '55'),
    Country(
        name: 'British Indian Ocean Territory', code: 'IO', phoneCode: '246'),
    Country(name: 'British Virgin Islands', code: 'VG', phoneCode: '1-284'),
    Country(name: 'Brunei', code: 'BN', phoneCode: '673'),
    Country(name: 'Bulgaria', code: 'BG', phoneCode: '359'),
    Country(name: 'Burkina Faso', code: 'BF', phoneCode: '226'),
    Country(name: 'Burundi', code: 'BI', phoneCode: '257'),
    Country(name: 'Cambodia', code: 'KH', phoneCode: '855'),
    Country(name: 'Cameroon', code: 'CM', phoneCode: '237'),
    Country(name: 'Canada', code: 'CA', phoneCode: '1'),
    Country(name: 'Cape Verde', code: 'CV', phoneCode: '238'),
    Country(name: 'Cayman Islands', code: 'KY', phoneCode: '1-345'),
    Country(name: 'Central African Republic', code: 'CF', phoneCode: '236'),
    Country(name: 'Chad', code: 'TD', phoneCode: '235'),
    Country(name: 'Chile', code: 'CL', phoneCode: '56'),
    Country(name: 'China', code: 'CN', phoneCode: '86'),
    Country(name: 'Christmas Island', code: 'CX', phoneCode: '61'),
    Country(name: 'Cocos Islands', code: 'CC', phoneCode: '61'),
    Country(name: 'Colombia', code: 'CO', phoneCode: '57'),
    Country(name: 'Comoros', code: 'KM', phoneCode: '269'),
    Country(name: 'Congo', code: 'CG', phoneCode: '242'),
    Country(name: 'D.R of the Congo', code: 'CD', phoneCode: '243'),
    Country(name: 'Cook Islands', code: 'CK', phoneCode: '682'),
    Country(name: 'Costa Rica', code: 'CR', phoneCode: '506'),
    Country(name: "Côte d'Ivoire", code: 'CI', phoneCode: '225'),
    Country(name: 'Croatia', code: 'HR', phoneCode: '385'),
    Country(name: 'Cuba', code: 'CU', phoneCode: '53'),
    Country(name: 'Cyprus', code: 'CY', phoneCode: '357'),
    Country(name: 'Czech Republic', code: 'CZ', phoneCode: '420'),
    Country(name: 'Denmark', code: 'DK', phoneCode: '45'),
    Country(name: 'Djibouti', code: 'DJ', phoneCode: '253'),
    Country(name: 'Dominica', code: 'DM', phoneCode: '1-767'),
    Country(name: 'Dominican Republic', code: 'DO', phoneCode: '1-809'),
    Country(name: 'Ecuador', code: 'EC', phoneCode: '593'),
    Country(name: 'Egypt', code: 'EG', phoneCode: '20'),
    Country(name: 'El Salvador', code: 'SV', phoneCode: '503'),
    Country(name: 'Equatorial Guinea', code: 'GQ', phoneCode: '240'),
    Country(name: 'Eritrea', code: 'ER', phoneCode: '291'),
    Country(name: 'Estonia', code: 'EE', phoneCode: '372'),
    Country(name: 'Ethiopia', code: 'ET', phoneCode: '251'),
    Country(name: 'Falkland Islands', code: 'FK', phoneCode: '500'),
    Country(name: 'Faroe Islands', code: 'FO', phoneCode: '298'),
    Country(name: 'Fiji', code: 'FJ', phoneCode: '679'),
    Country(name: 'Finland', code: 'FI', phoneCode: '358'),
    Country(name: 'France', code: 'FR', phoneCode: '33'),
    Country(name: 'French Guiana', code: 'GF', phoneCode: '594'),
    Country(name: 'French Polynesia', code: 'PF', phoneCode: '689'),
    Country(name: 'Gabon', code: 'GA', phoneCode: '241'),
    Country(name: 'Gambia', code: 'GM', phoneCode: '220'),
    Country(name: 'Georgia', code: 'GE', phoneCode: '995'),
    Country(name: 'Germany', code: 'DE', phoneCode: '49'),
    Country(name: 'Ghana', code: 'GH', phoneCode: '233'),
    Country(name: 'Gibraltar', code: 'GI', phoneCode: '350'),
    Country(name: 'Greece', code: 'GR', phoneCode: '30'),
    Country(name: 'Greenland', code: 'GL', phoneCode: '299'),
    Country(name: 'Grenada', code: 'GD', phoneCode: '1-473'),
    Country(name: 'Guadeloupe', code: 'GP', phoneCode: '590'),
    Country(name: 'Guam', code: 'GU', phoneCode: '1-671'),
    Country(name: 'Guatemala', code: 'GT', phoneCode: '502'),
    Country(name: 'Guinea', code: 'GN', phoneCode: '224'),
    Country(name: 'Guinea-Bissau', code: 'GW', phoneCode: '245'),
    Country(name: 'Guyana', code: 'GY', phoneCode: '592'),
    Country(name: 'Haiti', code: 'HT', phoneCode: '509'),
    Country(name: 'Honduras', code: 'HN', phoneCode: '504'),
    Country(name: 'Hong Kong', code: 'HK', phoneCode: '852'),
    Country(name: 'Hungary', code: 'HU', phoneCode: '36'),
    Country(name: 'Iceland', code: 'IS', phoneCode: '354'),
    Country(name: 'India', code: 'IN', phoneCode: '91'),
    Country(name: 'Indonesia', code: 'ID', phoneCode: '62'),
    Country(name: 'Iran', code: 'IR', phoneCode: '98'),
    Country(name: 'Iraq', code: 'IQ', phoneCode: '964'),
    Country(name: 'Ireland', code: 'IE', phoneCode: '353'),
    Country(name: 'Italy', code: 'IT', phoneCode: '39'),
    Country(name: 'Jamaica', code: 'JM', phoneCode: '1-876'),
    Country(name: 'Japan', code: 'JP', phoneCode: '81'),
    Country(name: 'Jordan', code: 'JO', phoneCode: '962'),
    Country(name: 'Kazakhstan', code: 'KZ', phoneCode: '7'),
    Country(name: 'Kenya', code: 'KE', phoneCode: '254'),
    Country(name: 'Kiribati', code: 'KI', phoneCode: '686'),
    Country(name: 'North Korea', code: 'KP', phoneCode: '850'),
    Country(name: 'South Korea', code: 'KR', phoneCode: '82'),
    Country(name: 'Kuwait', code: 'KW', phoneCode: '965'),
    Country(name: 'Kyrgyzstan', code: 'KG', phoneCode: '996'),
    Country(name: 'Laos', code: 'LA', phoneCode: '856'),
    Country(name: 'Latvia', code: 'LV', phoneCode: '371'),
    Country(name: 'Lebanon', code: 'LB', phoneCode: '961'),
    Country(name: 'Lesotho', code: 'LS', phoneCode: '266'),
    Country(name: 'Liberia', code: 'LR', phoneCode: '231'),
    Country(name: 'Libya', code: 'LY', phoneCode: '218'),
    Country(name: 'Lithuania', code: 'LT', phoneCode: '370'),
    Country(name: 'Luxembourg', code: 'LU', phoneCode: '352'),
    Country(name: 'Macao', code: 'MO', phoneCode: '853'),
    Country(name: 'Macedonia', code: 'MK', phoneCode: '389'),
    Country(name: 'Madagascar', code: 'MG', phoneCode: '261'),
    Country(name: 'Malawi', code: 'MW', phoneCode: '265'),
    Country(name: 'Malaysia', code: 'MY', phoneCode: '60'),
    Country(name: 'Maldives', code: 'MV', phoneCode: '960'),
    Country(name: 'Mali', code: 'ML', phoneCode: '223'),
    Country(name: 'Malta', code: 'MT', phoneCode: '356'),
    Country(name: 'Marshall Islands', code: 'MH', phoneCode: '692'),
    Country(name: 'Martinique', code: 'MQ', phoneCode: '596'),
    Country(name: 'Mauritania', code: 'MR', phoneCode: '222'),
    Country(name: 'Mauritius', code: 'MU', phoneCode: '230'),
    Country(name: 'Mayotte', code: 'YT', phoneCode: '262'),
    Country(name: 'Mexico', code: 'MX', phoneCode: '52'),
    Country(name: 'Micronesia', code: 'FM', phoneCode: '691'),
    Country(name: 'Moldova', code: 'MD', phoneCode: '373'),
    Country(name: 'Monaco', code: 'MC', phoneCode: '377'),
    Country(name: 'Mongolia', code: 'MN', phoneCode: '976'),
    Country(name: 'Montenegro', code: 'ME', phoneCode: '382'),
    Country(name: 'Montserrat', code: 'MS', phoneCode: '1-664'),
    Country(name: 'Morocco', code: 'MA', phoneCode: '212'),
    Country(name: 'Mozambique', code: 'MZ', phoneCode: '258'),
    Country(name: 'Myanmar', code: 'MM', phoneCode: '95'),
    Country(name: 'Namibia', code: 'NA', phoneCode: '264'),
    Country(name: 'Nauru', code: 'NR', phoneCode: '674'),
    Country(name: 'Nepal', code: 'NP', phoneCode: '977'),
    Country(name: 'Netherlands', code: 'NL', phoneCode: '31'),
    Country(name: 'New Caledonia', code: 'NC', phoneCode: '687'),
    Country(name: 'New Zealand', code: 'NZ', phoneCode: '64'),
    Country(name: 'Nicaragua', code: 'NI', phoneCode: '505'),
    Country(name: 'Niger', code: 'NE', phoneCode: '227'),
    Country(name: 'Nigeria', code: 'NG', phoneCode: '234'),
    Country(name: 'Niue', code: 'NU', phoneCode: '683'),
    Country(name: 'Norfolk Island', code: 'NF', phoneCode: '672'),
    Country(name: 'Northern Mariana Islands', code: 'MP', phoneCode: '1-670'),
    Country(name: 'Norway', code: 'NO', phoneCode: '47'),
    Country(name: 'Oman', code: 'OM', phoneCode: '968'),
    Country(name: 'Pakistan', code: 'PK', phoneCode: '92'),
    Country(name: 'Palau', code: 'PW', phoneCode: '680'),
    Country(name: 'Panama', code: 'PA', phoneCode: '507'),
    Country(name: 'Papua New Guinea', code: 'PG', phoneCode: '675'),
    Country(name: 'Paraguay', code: 'PY', phoneCode: '595'),
    Country(name: 'Peru', code: 'PE', phoneCode: '51'),
    Country(name: 'Philippines', code: 'PH', phoneCode: '63'),
    Country(name: 'Pitcairn Islands', code: 'PN', phoneCode: '870'),
    Country(name: 'Poland', code: 'PL', phoneCode: '48'),
    Country(name: 'Portugal', code: 'PT', phoneCode: '351'),
    Country(name: 'Puerto Rico', code: 'PR', phoneCode: '1-787'),
    Country(name: 'Qatar', code: 'QA', phoneCode: '974'),
    Country(name: 'Réunion', code: 'RE', phoneCode: '262'),
    Country(name: 'Romania', code: 'RO', phoneCode: '40'),
    Country(name: 'Russia', code: 'RU', phoneCode: '7'),
    Country(name: 'Rwanda', code: 'RW', phoneCode: '250'),
    Country(name: 'Saint Barthélemy', code: 'BL', phoneCode: '590'),
    Country(name: 'Saint Helena', code: 'SH', phoneCode: '290'),
    Country(name: 'Saint Kitts and Nevis', code: 'KN', phoneCode: '1-869'),
    Country(name: 'Saint Lucia', code: 'LC', phoneCode: '1-758'),
    Country(name: 'Saint Martin', code: 'MF', phoneCode: '590'),
    Country(name: 'Saint Pierre and Miquelon', code: 'PM', phoneCode: '508'),
    Country(
        name: 'St Vincent and the Grenadines', code: 'VC', phoneCode: '1-784'),
    Country(name: 'Samoa', code: 'WS', phoneCode: '685'),
    Country(name: 'San Marino', code: 'SM', phoneCode: '378'),
    Country(name: 'Sao Tome and Principe', code: 'ST', phoneCode: '239'),
    Country(name: 'Saudi Arabia', code: 'SA', phoneCode: '966'),
    Country(name: 'Senegal', code: 'SN', phoneCode: '221'),
    Country(name: 'Serbia', code: 'RS', phoneCode: '381'),
    Country(name: 'Seychelles', code: 'SC', phoneCode: '248'),
    Country(name: 'Sierra Leone', code: 'SL', phoneCode: '232'),
    Country(name: 'Singapore', code: 'SG', phoneCode: '65'),
    Country(name: 'Sint Maarten', code: 'SX', phoneCode: '1-721'),
    Country(name: 'Slovakia', code: 'SK', phoneCode: '421'),
    Country(name: 'Slovenia', code: 'SI', phoneCode: '386'),
    Country(name: 'Solomon Islands', code: 'SB', phoneCode: '677'),
    Country(name: 'Somalia', code: 'SO', phoneCode: '252'),
    Country(name: 'South Africa', code: 'ZA', phoneCode: '27'),
    Country(name: 'South Sudan', code: 'SS', phoneCode: '211'),
    Country(name: 'Spain', code: 'ES', phoneCode: '34'),
    Country(name: 'Sri Lanka', code: 'LK', phoneCode: '94'),
    Country(name: 'Sudan', code: 'SD', phoneCode: '249'),
    Country(name: 'Suriname', code: 'SR', phoneCode: '597'),
    Country(name: 'Svalbard and Jan Mayen', code: 'SJ', phoneCode: '47'),
    Country(name: 'Swaziland', code: 'SZ', phoneCode: '268'),
    Country(name: 'Sweden', code: 'SE', phoneCode: '46'),
    Country(name: 'Switzerland', code: 'CH', phoneCode: '41'),
    Country(name: 'Syria', code: 'SY', phoneCode: '963'),
    Country(name: 'Taiwan', code: 'TW', phoneCode: '886'),
    Country(name: 'Tajikistan', code: 'TJ', phoneCode: '992'),
    Country(name: 'Tanzania', code: 'TZ', phoneCode: '255'),
    Country(name: 'Thailand', code: 'TH', phoneCode: '66'),
    Country(name: 'Timor-Leste', code: 'TL', phoneCode: '670'),
    Country(name: 'Togo', code: 'TG', phoneCode: '228'),
    Country(name: 'Tokelau', code: 'TK', phoneCode: '690'),
    Country(name: 'Tonga', code: 'TO', phoneCode: '676'),
    Country(name: 'Trinidad and Tobago', code: 'TT', phoneCode: '1-868'),
    Country(name: 'Tunisia', code: 'TN', phoneCode: '216'),
    Country(name: 'Turkey', code: 'TR', phoneCode: '90'),
    Country(name: 'Turkmenistan', code: 'TM', phoneCode: '993'),
    Country(name: 'Turks and Caicos Islands', code: 'TC', phoneCode: '1-649'),
    Country(name: 'Tuvalu', code: 'TV', phoneCode: '688'),
    Country(name: 'Uganda', code: 'UG', phoneCode: '256'),
    Country(name: 'Ukraine', code: 'UA', phoneCode: '380'),
    Country(name: 'United Arab Emirates', code: 'AE', phoneCode: '971'),
    Country(name: 'United Kingdom', code: 'GB', phoneCode: '44'),
    Country(name: 'United States', code: 'US', phoneCode: '1'),
    Country(name: 'Uruguay', code: 'UY', phoneCode: '598'),
    Country(name: 'Uzbekistan', code: 'UZ', phoneCode: '998'),
    Country(name: 'Vanuatu', code: 'VU', phoneCode: '678'),
    Country(name: 'Vatican City', code: 'VA', phoneCode: '379'),
    Country(name: 'Venezuela', code: 'VE', phoneCode: '58'),
    Country(name: 'Vietnam', code: 'VN', phoneCode: '84'),
    Country(name: 'Virgin Islands, British', code: 'VG', phoneCode: '1-284'),
    Country(name: 'Virgin Islands, U.S.', code: 'VI', phoneCode: '1-340'),
    Country(name: 'Wallis and Futuna', code: 'WF', phoneCode: '681'),
    Country(name: 'Western Sahara', code: 'EH', phoneCode: '212'),
    Country(name: 'Yemen', code: 'YE', phoneCode: '967'),
    Country(name: 'Zambia', code: 'ZM', phoneCode: '260'),
    Country(name: 'Zimbabwe', code: 'ZW', phoneCode: '263'),
  ];
}
